# Generated by Django 6.0.3 on 2026-03-21 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_sh', models.CharField(max_length=10, verbose_name='Code SH')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['code_sh'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_iso', models.CharField(max_length=3, unique=True)),
                ('continent', models.CharField(choices=[('afrique', 'Afrique'), ('europe', 'Europe'), ('asie', 'Asie'), ('amerique_nord', 'Amérique du Nord'), ('amerique_sud', 'Amérique du Sud'), ('oceanie', 'Océanie')], max_length=20)),
                ('bloc_economique', models.CharField(choices=[('cedeao', 'CEDEAO'), ('ue', 'Union Européenne'), ('ua', 'Union Africaine'), ('asean', 'ASEAN'), ('mercosur', 'MERCOSUR'), ('alena', 'ALENA/ACEUM'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('population', models.BigIntegerField(default=0)),
                ('pib', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Pays',
                'ordering': ['continent', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('litre', 'Litre'), ('unite', 'Unité'), ('m3', 'Mètre cube'), ('baril', 'Baril')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='commerce.categorieproduit')),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('importation', 'Importation'), ('exportation', 'Exportation')], max_length=15)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valeur_totale', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_transaction', models.DateField()),
                ('numero_declaration', models.CharField(max_length=50, unique=True)),
                ('mode_transport', models.CharField(choices=[('maritime', 'Maritime'), ('aerien', 'Aérien'), ('terrestre', 'Terrestre'), ('ferroviaire', 'Ferroviaire')], max_length=15)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='valide', max_length=10)),
                ('pays_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destination', to='commerce.pays')),
                ('pays_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_origine', to='commerce.pays')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='commerce.produit')),
            ],
            options={
                'ordering': ['-date_transaction'],
            },
        ),
    ]
