# Generated by Django 6.0.3 on 2026-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type_transaction', 'statut'], name='commerce_tr_type_tr_b57623_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date_transaction'], name='commerce_tr_date_tr_740924_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['statut'], name='commerce_tr_statut_8537ce_idx'),
        ),
    ]
